---
- type: replace
  path: /instance_groups/name=bosh/properties/lxd_cpi/server/instance_config?
  value: ((server_instance_config))

- type: replace
  path: /cloud_provider/properties/lxd_cpi/server/instance_config?
  value: ((server_instance_config))
